name:                revision
version:             0.1.0.0
github:              "mbg/revision"
license:             BSD3
author:              "Michael B. Gale"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright 2018 Michael B. Gale"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbg/revision#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
    - GADTs
    - DataKinds
    - TypeFamilies
    - KindSignatures
    - FlexibleInstances
    - ScopedTypeVariables

library:
  source-dirs: src

executables:
  revision-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - revision

tests:
  revision-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - revision
